### ISSUE TITLE
Add option to list all versions for a cloudlet policy ID and which version is active in which network

### ISSUE THREAD

**Issue by cvannada** [akamai/cli-cloudlets#11]
Please add cli-cloudlets functionality to list all versions for a cloudlet policy ID and which version is active in prod or staging. Fields required in output: policyID | Version | Last Modified | Last Editor | Notes | Staging Status | Production Status. This will be useful to prevent needing the UI to get this info when a very large number of policyIDs exist. It also helps determine which pre-configured version of a cloudlet should be activated based on the version notes and the functionality needed with that version.

**Comment by pwongcha** [comment]
@cvannada  this is available now. please run `akamai update cloudlets` to get the latest version

**Comment by pwongcha** [comment]
#12 merged into master.  @cvannada confirmed the result
