### ISSUE TITLE
Adding help command

### ISSUE THREAD

**Issue by wzagrajcz** [akamai/cli-cloudlets#14]
Hi,
One of the recent (up to 4 months probably) commits changed the access to help from `akamai cloudlets help` to `akamai cloudlets -h`.  Alongside with this change, the following command `akamai help cloudlets` stopped working (which in fact is calling `akamai cloudlets help` underneath). Other cli-packages follow the help as command approach and to keep the UX consistent it would be great have it here as well.

Can You please add calling help though the command back in this project and `cli-onboard`?

Best regards,
Wojciech

**Comment by pwongcha** [comment]
Acknowledge.  If I don't get this done by end of month, feel free to nudge me again :)
