### ISSUE TITLE
Activate existing load balancing version

### ISSUE THREAD

**Issue by Firenzzz** [akamai/cli-cloudlets#27]
Hi,

https://github.com/akamai/cli-cloudlets/blob/39274289eb86ee9396b3b611f500a63676eb70cb/bin/cloudlet_api_wrapper.py#L531

any idea when will this get activated? I'm looking for a solution that will allow me to tell "activate version 3 on 1234_QA". At the moment alb-update only supports updating a description.

Thanks.

**Comment by janpatel94** [comment]
@Firenzzz  this has being added in branch: GH29-alb-lb-id-features along with few other options (clone lb id and updating percentage) and currently being tested.

**Comment by pwongcha** [comment]
please update cloudlets version to v1.2.0
```
akamai update cloudlets 

# if update fails, try 2 commands below
akamai uninstall cloudlets
akamai install cloudlets

akamai cloudlets --version   
```
please try new command `alb-clone-lb` then `alb-lb-activate`
let us know if there's any issue.
