### ISSUE TITLE
ALB Load balancing policy feature request

### ISSUE THREAD

**Issue by JaneiLPateL** [akamai/cli-cloudlets#29]
### ALB Load balancing cloudlet activation

Functionality to update existing load balancing id with the following features is missing

- Percentage update for datacenters
- Add / Remove Datacenter 
- Activate load balancing policies

**Comment by janpatel94** [comment]
Branch 'GH29-alb-lb-id-features' has the new features if anyone is actively following this and wants to test. Working towards documentation and testing it at the moment.
