### ISSUE TITLE
akamai cloudlets list fail to show the results of the shared policies

### ISSUE THREAD

**Issue by nyadav2019** [akamai/cli-cloudlets#3]
Hi Team,

We have customer, who fail to see the share policies in the  below commands:
$ **akamai cloudlets status  --policy <Shared policy Name>**
...searching for cloudlet policy <Shared policy Name>
_ERROR: Unable to find existing policy_

**C:\Users\<User>\Desktop>akamai cloudlets list**

I did the research and found that the current code is  still using the API v2 instead of API v3, please refer to the below doc:
https://techdocs.akamai.com/cloudlets/reference/get-policies
https://techdocs.akamai.com/cloudlets/reference/api-concepts

**Comment by vreddhi** [comment]
@nyadav2019 
The CLI is not using v3 APIs. Curious to know how many policies are you looking to manage as shared policies?

**Comment by aarondotsteele** [comment]
We are running into the same issue. Currently, we have about 12 policies that are shared, but will continue to use more and more. We use Forward Rewrite, Edge Redirector, Request Control, and ALB Cloudlets.

**Comment by aarondotsteele** [comment]
Looks like the other issue is that v3 ONLY returns shared policies, while v2 ONLY returns old policies. Solution seems to be either to create a new cli-c3 library or a flag on this one to test for shared on not shared policies...

**Comment by saratrajan** [comment]
Oh boy, we are having the same issue as well. All our policy are `not-shared` as of now but that comes with a pain-point of activating the policy whenever a new property is on-boarded to Akamai. Having Shared policy in place gets rid of this additional overhead and we would like to get most policies converted to (somehow) Shared mode.
Since CLI does not show any love to Shared policy-type as of today is there a way to get this enabled so that we are able to make use of the cloudlets-cli to list, create, clone and update Shared policies sooner?

Cheers,
Sarat

**Comment by brucep-care** [comment]
Ugh, we're encountering this as well as we start backporting some of our cloudlets into terraform. Will this also be an issue within the Akamai terraform provider?

**Comment by scottwallacesh** [comment]
> Ugh, we're encountering this as well as we start backporting some of our cloudlets into terraform. Will this also be an issue within the Akamai terraform provider?

It certainly seems to be.  I was able to `akamai terraform export-cloudlets-policy ...` a non-shared policy but trying with a shared policy just returns a `unable to fetch policy with given name ...` error.

**Comment by aarondotsteele** [comment]
I was able to make a v3 version of the cloudlets cli locally. Super hacky, but the diffs aren't that big. It would be nice to have a flag or something that you could switch between the two until the api supports both...

**Comment by aarondotsteele** [comment]
> Will you submit a PR?

It's not really something that can be merged. It's an overwrite that only works with v3. Here is a zip of it.
[cli-cloudlets-v3.zip](https://github.com/akamai/cli-cloudlets/files/9831136/cli-cloudlets-v3.zip)
