### ISSUE TITLE
Update Cloudlet policy by policy name broken

### ISSUE THREAD

**Issue by pmsandip** [akamai/cli-cloudlets#4]
It seems via the Akamai Cloudlets CLI, I am unable to update the cloudlet policy using the policy name. However, when I use the policy ID, it seems to work. Is that a bug in CLI that it is unable to locate the policy using its name? It would be helpful if this is fixed because in our automation workflows, it would be easier if we used everything CLI instead of trying to use CLI for some operations and API for some others.

**Comment by vreddhi** [comment]
Thank you for raising this @pmsandip . It appears to be a pagination issue. We will look into this.
Tagging @aetsai

**Comment by aetsai** [comment]
should be fixed with v1.0.1
