### ISSUE TITLE
Some Cloudlets CLI commands do not provide with --edgerc option

### ISSUE THREAD

**Issue by pmsandip** [akamai/cli-cloudlets#5]
It seems like some of the cloudlets CLI commands like 'akamai cloudlets update' and 'akamai cloudlets activate' do NOT provide an option to override the path to .edgerc file using the --edgerc option. This becomes challenging in an automation workflow like jenkins where it seems to look for edgerc file under home dir and jenkins wouldn't allow to write to the home dir.

**Comment by vreddhi** [comment]
Every command in CLI does accept --edgerc, as its a common codeflow across commands. Example command would be:

`akamai cloudlets --edgerc '<cred_file>' update <policy-name/id> ....`

**Comment by pmsandip** [comment]
@vreddhi thanks, for the update. It looks like the order of the arguments do matter here. I was using the --edgerc option after the update or activate command. Sorry for the false alarm.
