### ISSUE TITLE
cloudlets not found after upgrading akamai.exe to v1.5.1

### ISSUE THREAD

**Issue by dwishnek** [akamai/cli-cloudlets#6]
After upgrading akamai.exe from 1.2.1 to v1.5.1, I receive the following error..

c:\Users\xxx\Documents\Git\akamai>akamai cloudlets status --policy PROD_Access_Control
? New upgrade found: v1.5.1 (you are running: 1.2.1). Upgrade now? [Y/n]:  Yes
Upgrading Akamai CLI ... [OK]
 ERROR[0000] Executable "cloudlets" not found. command=cloudlets
←[31mExecutable "cloudlets" not found.←[0m

Prior to upgrade, akamai.exe was working...

**Comment by vreddhi** [comment]
Prior to the upgrade was `akamai cloudlets` working? May i request you to try installing cloudlets module again?

`akamai install cloudlets`

**Comment by dwishnek** [comment]
Hi, yes The Akamai.exe version prior to upgrade was working. As a matter of fact, if I copy the old aklamai.exe over the upgraded one, it works still.. It only fails if I am running the new version..

When I type “akamai install cloudlets”, I get…

Attempting to fetch command from https://github.com/akamai/cli-cloudlets.git<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2Fgithub.com%2Fakamai%2Fcli-cloudlets.git__%3B!!GjvTz_vk!R-lK5ikuiX8IbT7GOKWQUuCSGaQyfljbUz1uhLwPoA48IyPUN5_ch-r3TKQwKxu9kqmqVj2q89xwp19aKMpBa3Ui_Q%24&data=05%7C01%7Cdon.wishnek%40aciworldwide.com%7Ca6bc96e024614559442608da4f0f72fd%7Cd1b7f1185cb24d4e85a382e07efb07e9%7C1%7C0%7C637909225045383110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1RlmOMty%2B25T%2BncD4DZuSm1KhRX05qeSGLRZw8r1EEQ%3D&reserved=0>... ... [WARN]
←[33mPackage directory already exists (C:\Users\wishnekd\.akamai-cli\src\cli-cloudlets). To reinstall this package, first run 'akamai uninstall' command.←[0m






Don Wishnek
DevOPS
T +1 212 361 7302 / M +1 704 608 8016
***@***.******@***.***>

Upcoming Out of Office:

**Comment by vreddhi** [comment]
This issue would be more relevant to the base CLI package, and not the cloudlets module.

May I request you to raise an issue here?
https://github.com/akamai/cli/issues

As a quick fix or work-around, you could try 
`akamai uninstall cloudlets` and `akamai install cloudlets`

**Comment by pwongcha** [comment]
akamai cli is now on version 1.5.2
Do you still have an issue? @dwishnek

**Comment by pwongcha** [comment]
The issue is stale; therefore, we will proceed to close it.
